name: start-test-windows-powershell

on:
  workflow_dispatch:

jobs:
  start-test-windows:
    runs-on: ubuntu-latest
    steps:
      - name: dowland code
        uses: actions/checkout@v4

      - name: setup instances
        run: ./windows-scripts/build_and_run.ps1 8081 8082 8083
        shell: pwsh

      - name: wait for start
        run: Start-Sleep -Seconds 60
        shell: pwsh

      - name: send curl
        run: | 
          curl -X GET http://localhost:8081/stocks -H "Content-Type: application/json"
          if ($LASTEXITCODE -ne 0) { exit 1 }
        shell: pwsh

      - name: remove
        run: ./windows-scripts/remove.ps1
        shell: pwsh